version: '3.8'
services:
  minio:
    restart: always
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fedn_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
  mongo:
    restart: always
    image: mongo:7.0
    command: mongod --port 6534
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-fedn_admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - "6534:6534"
    volumes:
      - ./storage/mongo:/data/db
  api-server:
    restart: always
    image: ${DOCKER_IMAGE}
    working_dir: /app
    command: ["controller","start","--init","/app/config/controller.yaml"]
    environment:
      STATESTORE_CONFIG: /app/config/controller.yaml
      MODELSTORAGE_CONFIG: /app/config/controller.yaml
      FEDN_COMPUTE_PACKAGE_DIR: /app/storage
      TMPDIR: /app/tmp
    depends_on:
      - minio
      - mongo
    ports:
      - "8092:8092"
    volumes:
      - ./config:/app/config
      - ./storage:/app/storage
  hooks:
    restart: always
    image: ${DOCKER_IMAGE}
    working_dir: /app
    command: ["hooks","start","--init","/app/config/hooks.yaml"]
    environment:
      TMPDIR: /app/tmp
    depends_on:
      - api-server
    ports:
      - "12081:12081"
    volumes:
      - ./config:/app/config
  combiner:
    restart: always
    image: ${DOCKER_IMAGE}
    working_dir: /app
    command: ["combiner","start","--init","/app/config/combiner.yaml"]
    environment:
      TMPDIR: /app/tmp
    depends_on:
      - api-server
      - hooks
    ports:
      - "12080:12080"
    volumes:
      - ./config:/app/config
networks:
  default:
    driver: bridge
