version: '3.8'
services:
  fedn-client-1:
    image: ${DOCKER_IMAGE}
    working_dir: /app/client
    command: ["client","start","--combiner","${COMBINER_HOST}","--combiner-port","12080","--in","fedn.yaml","--name","client-${CLIENT_ID_1}","--local-package"]
    environment:
      FEDN_CLIENT_ID: ${CLIENT_ID_1}
    volumes:
      - ./fedn.yaml:/app/client/fedn.yaml
      - ../logs:/app/logs
  fedn-client-2:
    image: ${DOCKER_IMAGE}
    working_dir: /app/client
    command: ["client","start","--combiner","${COMBINER_HOST}","--combiner-port","12080","--in","fedn.yaml","--name","client-${CLIENT_ID_2}","--local-package"]
    environment:
      FEDN_CLIENT_ID: ${CLIENT_ID_2}
    volumes:
      - ./fedn.yaml:/app/client/fedn.yaml
      - ../logs:/app/logs
networks:
  default:
    driver: bridge
